apiVersion: v1
kind: ConfigMap 
metadata:
  name: configmap 
data:
  POSTGRES_DB: "project-postgresql-db"
  POSTGRES_USER: "ibrahim"
  POSTGRES_HOST: "project-postgresql-server.postgres.database.azure.com"
